# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'pocket-ios-client' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for pocket-ios-client

  pod 'Starscream'
  pod 'RealmSwift'

end
